workflow filesupdate
workflow files update

diff --git a/.github/workflows/higher_env_workflow.yml b/.github/workflows/higher_env_workflow.yml
--- a/.github/workflows/higher_env_workflow.yml
+++ b/.github/workflows/higher_env_workflow.yml
@@ -6,6 +6,11 @@ on:
   push:
     branches: [ releases/** ]
   workflow_dispatch:
+    inputs:
+      isPolicyNeeded:
+        description: 'Flag to decide if policy execution is needed'     
+        required: true
+        default: 'true'
 
 jobs:
   #This job builds and publishes the artifact to Exchange and stores backup in GitHub
@@ -21,10 +26,32 @@ jobs:
       SECURE_ENCRYPT_KEY: "${{ secrets.MULE_SIT_SECURE_ENCRYPT_KEY }}"
       MULE_NEXUS_REPO_EE_USERNAME: "${{ secrets.MULE_NEXUS_REPO_EE_USERNAME }}"
       MULE_NEXUS_REPO_EE_PWD: "${{ secrets.MULE_NEXUS_REPO_EE_PWD }}"
+      SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
+      SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
 
+  pre-deploy-sit-01:
+    runs-on: ubuntu-20.04
+    needs: build-sit-01
+    environment:
+      name: "SIT"
+    outputs:
+      output1: ${{ steps.RunScriptFile.outputs.API_ID }}
+    steps:
+    - uses: actions/checkout@v2
+    - id: RunScriptFile
+      run: |
+         npm install -g anypoint-cli-v4
+         sudo apt-get update && sudo apt-get -qq -y install jq  
+         sudo apt install libxml2-utils
+         chmod +x scripts/deploymentAutomationScript.sh
+         ./scripts/deploymentAutomationScript.sh "SIT" ${{ secrets.MULE_AP_CLI_CLIENT_ID }} ${{ secrets.MULE_AP_CLI_CLIENT_SECRET }} ${{ secrets.MULE_PARENT_BIZ_GROUP }} pom.xml ${{ vars.DEPLOYMENT_TYPE }} ${{ vars.PRE_DEPLOYMENT_ACTION }} > ./result.txt
+         cat result.txt
+         echo "API_ID=$(cat result.txt | grep "APIId:" | cut -d":" -f2)" >> $GITHUB_OUTPUT
+      shell: bash
+      
   #This job deploys the application to SIT environment with provided configuration details; upon APPROVAL from the aprrovers
   deploy-sit-01:
-    needs: [build-sit-01]
+    needs: pre-deploy-sit-01
     uses: am-cicd/ms-devops-workflow-main/.github/workflows/deploy_workflow.yml@main
     with:
       CLOUDHUB_ENVIRONMENT: "SIT"
@@ -34,15 +61,9 @@ jobs:
       CLOUDHUB_PRIVATE_SPACE: "${{ vars.MULE_NONPROD_CLOUDHUB_PRIVATE_SPACE }}"
       CLOUDHUB_PUBLIC_URL: "" #Provide the Endpoint URL if custom public endpoint is needed
       GENERATE_PUBLIC_URL_FLAG: "false" #Set to true only if the app has public Endpoint URL; in all other cases this should be false
-      APP_LAYER: ${{ vars.MULE_SYS_API_LAYER  }}
-      CLUSTER_ENABLED_FLAG: "false" #Set to true if needed;
-      #Begin S3 Logging Properties
-      MULE_LOG_S3_FREQUENCY_MIN: "${{ vars.MULE_NONPROD_LOG_S3_FREQUENCY_MIN }}"
-      MULE_LOG_S3_AWS_REGION: "${{ vars.MULE_LOG_S3_AWS_REGION }}"
-      MULE_LOG_S3_AWS_BUCKET: "${{ vars.MULE_SIT_LOG_S3_AWS_BUCKET }}"
-      MULE_LOG_S3_COMPRESS_FLAG: "${{ vars.MULE_LOG_S3_COMPRESS_FLAG }}"
-      MULE_LOG_S3_STORAGE_CLASS: "${{ vars.MULE_LOG_S3_STORAGE_CLASS }}"
-      #End S3 Logging Properties
+      APP_LAYER: ${{ vars.MULE_SYS_API_LAYER }}
+      APP_VERSION: "v1"
+      API_ID: "${{ needs.pre-deploy-sit-01.outputs.output1 }}"
     secrets:
       EX_CONNECTED_APP_ID: "${{ secrets.MULE_EX_CONNECTED_APP_ID }}"
       EX_CONNECTED_APP_SECRET: "${{ secrets.MULE_EX_CONNECTED_APP_SECRET }}"
@@ -50,16 +71,68 @@ jobs:
       CH_CONNECTED_APP_SECRET: "${{ secrets.MULE_NONPROD_CH_CONNECTED_APP_SECRET }}"
       MULE_AP_CLIENT_ID: "${{ secrets.MULE_AP_CLIENT_ID }}"
       MULE_AP_CLIENT_SECRET: "${{ secrets.MULE_AP_CLIENT_SECRET }}"
-      TITAN_BIZ_GROUP: "${{ secrets.MULE_TITAN_BIZ_GROUP }}"
+      BIZ_GROUP: "${{ secrets.MULE_PARENT_BIZ_GROUP }}"
       SECURE_ENCRYPT_KEY: "${{ secrets.MULE_SIT_SECURE_ENCRYPT_KEY }}"
-      #Begin S3 Logging Properties
-      MULE_AWS_S3_ACCESS_KEY: "${{ secrets.MULE_NONPROD_AWS_S3_ACCESS_KEY }}"
-      MULE_AWS_S3_SECRET_KEY: "${{ secrets.MULE_NONPROD_AWS_S3_SECRET_KEY }}"
-      #End S3 Logging Properties
 
+#Post Deployment Job
+  post-deploy-sit-01:
+    if: ${{ github.event.inputs.isPolicyNeeded == '' || github.event.inputs.isPolicyNeeded == 'true' }}
+    runs-on: ubuntu-20.04
+    needs: deploy-sit-01
+    environment:
+      name: "SIT"
+    env:
+      policyFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/policies.yaml"
+      postmanCollectionFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/collection/Email-Sapi.postman_collection.json"
+      postmanEnvFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/collection/SIT.postman_environment.json"
+    steps:
+    - uses: actions/checkout@v2
+    - id: RunPostDeploymentScriptFile
+      run: |
+         npm install -g anypoint-cli-v4
+         sudo apt-get update && sudo apt-get -qq -y install jq  
+         sudo apt install libxml2-utils
+         sudo snap install yq
+         chmod +x scripts/deploymentAutomationScript.sh
+         ./scripts/deploymentAutomationScript.sh "SIT" ${{ secrets.MULE_AP_CLI_CLIENT_ID }} ${{ secrets.MULE_AP_CLI_CLIENT_SECRET }} ${{ secrets.MULE_PARENT_BIZ_GROUP }} pom.xml ${{ vars.DEPLOYMENT_TYPE }} ${{ vars.POST_DEPLOYMENT_ACTION }} $policyFile
+    - name: Run postman scripts
+      run: |
+         npm install -g newman
+         npm install -g newman-reporter-htmlextra
+         sleep 60
+         newman run $postmanCollectionFile -e $postmanEnvFile
+          if [ $? -eq 0 ]; then
+            echo "All tests passed successfully."
+          else
+            echo "There were test failures."
+          fi
+      shell: bash
+
+  #Pre deployment Job
+  pre-deploy-uat-01:
+      runs-on: ubuntu-20.04
+      needs: post-deploy-sit-01
+      environment:
+        name: "UAT"
+      outputs:
+        output1: ${{ steps.RunScriptFile.outputs.API_ID }}
+      steps:
+      - uses: actions/checkout@v2
+      - id: RunScriptFile
+        run: |
+         npm install -g anypoint-cli-v4
+         sudo apt-get update && sudo apt-get -qq -y install jq  
+         sudo apt install libxml2-utils
+         chmod +x scripts/deploymentAutomationScript.sh
+         ./scripts/deploymentAutomationScript.sh "UAT" ${{ secrets.MULE_HG_CLI_CLIENT_ID }} ${{ secrets.MULE_HG_CLI_CLIENT_SECRET }} ${{ secrets.MULE_PARENT_BIZ_GROUP }} pom.xml ${{ vars.DEPLOYMENT_TYPE }} ${{ vars.PRE_DEPLOYMENT_ACTION }} > ./result.txt
+         cat result.txt
+         echo "API_ID=$(cat result.txt | grep "APIId:" | cut -d":" -f2)" >> $GITHUB_OUTPUT
+        shell: bash 
+  
+  
   #This job deploys the application to UAT environment with provided configuration details; upon APPROVAL from the aprrovers
   deploy-uat-01:
-    needs: [deploy-sit-01]
+    needs: pre-deploy-uat-01
     uses: am-cicd/ms-devops-workflow-main/.github/workflows/deploy_workflow.yml@main
     with:
       CLOUDHUB_ENVIRONMENT: "UAT"
@@ -69,15 +142,9 @@ jobs:
       CLOUDHUB_PRIVATE_SPACE: "${{ vars.MULE_NONPROD_CLOUDHUB_PRIVATE_SPACE }}"
       CLOUDHUB_PUBLIC_URL: "" #Provide the Endpoint URL if custom public endpoint is needed
       GENERATE_PUBLIC_URL_FLAG: "false" #Set to true only if the app has public Endpoint URL; in all other cases this should be false
-      APP_LAYER: ${{ vars.MULE_SYS_API_LAYER  }}
-      CLUSTER_ENABLED_FLAG: "false" #Set to true if needed;
-      #Begin S3 Logging Properties
-      MULE_LOG_S3_FREQUENCY_MIN: "${{ vars.MULE_NONPROD_LOG_S3_FREQUENCY_MIN }}"
-      MULE_LOG_S3_AWS_REGION: "${{ vars.MULE_LOG_S3_AWS_REGION }}"
-      MULE_LOG_S3_AWS_BUCKET: "${{ vars.MULE_UAT_LOG_S3_AWS_BUCKET }}"
-      MULE_LOG_S3_COMPRESS_FLAG: "${{ vars.MULE_LOG_S3_COMPRESS_FLAG }}"
-      MULE_LOG_S3_STORAGE_CLASS: "${{ vars.MULE_LOG_S3_STORAGE_CLASS }}"
-      #End S3 Logging Properties
+      APP_LAYER: ${{ vars.MULE_SYS_API_LAYER }}
+      APP_VERSION: "v1"
+      API_ID: "${{ needs.pre-deploy-uat-01.outputs.output1 }}"
     secrets:
       EX_CONNECTED_APP_ID: "${{ secrets.MULE_EX_CONNECTED_APP_ID }}"
       EX_CONNECTED_APP_SECRET: "${{ secrets.MULE_EX_CONNECTED_APP_SECRET }}"
@@ -85,34 +152,80 @@ jobs:
       CH_CONNECTED_APP_SECRET: "${{ secrets.MULE_NONPROD_CH_CONNECTED_APP_SECRET }}"
       MULE_AP_CLIENT_ID: "${{ secrets.MULE_AP_CLIENT_ID }}"
       MULE_AP_CLIENT_SECRET: "${{ secrets.MULE_AP_CLIENT_SECRET }}"
-      TITAN_BIZ_GROUP: "${{ secrets.MULE_TITAN_BIZ_GROUP }}"
+      BIZ_GROUP: "${{ secrets.MULE_PARENT_BIZ_GROUP }}"
       SECURE_ENCRYPT_KEY: "${{ secrets.MULE_UAT_SECURE_ENCRYPT_KEY }}"
-      #Begin S3 Logging Properties
-      MULE_AWS_S3_ACCESS_KEY: "${{ secrets.MULE_NONPROD_AWS_S3_ACCESS_KEY }}"
-      MULE_AWS_S3_SECRET_KEY: "${{ secrets.MULE_NONPROD_AWS_S3_SECRET_KEY }}"
-      #End S3 Logging Properties
 
+  #Post Deployment Job
+  post-deploy-uat-01:
+    if: ${{ github.event.inputs.isPolicyNeeded == '' || github.event.inputs.isPolicyNeeded == 'true' }}
+    runs-on: ubuntu-20.04
+    needs: deploy-uat-01
+    environment:
+      name: "UAT"
+    env:
+      policyFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/policies.yaml"
+      postmanCollectionFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/collection/Email-Sapi.postman_collection.json"
+      postmanEnvFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/collection/UAT.postman_environment.json"
+    steps:
+    - uses: actions/checkout@v2
+    - id: RunPostDeploymentScriptFile
+      run: |
+         npm install -g anypoint-cli-v4
+         sudo apt-get update && sudo apt-get -qq -y install jq  
+         sudo apt install libxml2-utils
+         sudo snap install yq
+         chmod +x scripts/deploymentAutomationScript.sh
+         ./scripts/deploymentAutomationScript.sh "UAT" ${{ secrets.MULE_HG_CLI_CLIENT_ID }} ${{ secrets.MULE_HG_CLI_CLIENT_SECRET }} ${{ secrets.MULE_PARENT_BIZ_GROUP }} pom.xml ${{ vars.DEPLOYMENT_TYPE }} ${{ vars.POST_DEPLOYMENT_ACTION }} $policyFile
+    - name: Run postman scripts
+      run: |
+         npm install -g newman
+         npm install -g newman-reporter-htmlextra
+         sleep 60
+         newman run $postmanCollectionFile -e $postmanEnvFile
+          if [ $? -eq 0 ]; then
+            echo "All tests passed successfully."
+          else
+            echo "There were test failures."
+          fi  
+      shell: bash
+
+  #Pre deployment Job
+  pre-deploy-prod-01:
+      runs-on: ubuntu-20.04
+      needs: post-deploy-uat-01
+      environment:
+        name: "PROD"
+      outputs:
+        output1: ${{ steps.RunScriptFile.outputs.API_ID }}
+      steps:
+      - uses: actions/checkout@v2
+      - id: RunScriptFile
+        run: |
+         npm install -g anypoint-cli-v4
+         sudo apt-get update && sudo apt-get -qq -y install jq  
+         sudo apt install libxml2-utils
+         chmod +x scripts/deploymentAutomationScript.sh
+         ./scripts/deploymentAutomationScript.sh "PROD" ${{ secrets.MULE_HG_CLI_CLIENT_ID }} ${{ secrets.MULE_HG_CLI_CLIENT_SECRET }} ${{ secrets.MULE_PARENT_BIZ_GROUP }} pom.xml ${{ vars.DEPLOYMENT_TYPE }} ${{ vars.PRE_DEPLOYMENT_ACTION }} > ./result.txt
+         cat result.txt
+         echo "API_ID=$(cat result.txt | grep "APIId:" | cut -d":" -f2)" >> $GITHUB_OUTPUT
+        shell: bash 
+        
   #This job deploys the application to PROD environment with provided configuration details; upon APPROVAL from the aprrovers
   deploy-prod-01:
-    needs: [deploy-uat-01]
+    needs: pre-deploy-prod-01
     uses: am-cicd/ms-devops-workflow-main/.github/workflows/deploy_workflow.yml@main
     with:
       CLOUDHUB_ENVIRONMENT: "PROD"
       GITHUB_ENVIRONMENT: "PROD"
-      CLOUDHUB_REPLICAS: "${{ vars.MULE_CLOUDHUB_REPLICAS_2 }}"
+      CLOUDHUB_REPLICAS: "${{ vars.MULE_CLOUDHUB_REPLICAS_1 }}"
       CLOUDHUB_REPLICA_SIZE: "${{ vars.MULE_CLOUDHUB_REPLICA_SIZE_0_1 }}"
       CLOUDHUB_PRIVATE_SPACE: "${{ vars.MULE_PROD_CLOUDHUB_PRIVATE_SPACE }}"
       CLOUDHUB_PUBLIC_URL: "" #Provide the Endpoint URL if custom public endpoint is needed
       GENERATE_PUBLIC_URL_FLAG: "false" #Set to true only if the app has public Endpoint URL; in all other cases this should be false
       APP_LAYER: ${{ vars.MULE_SYS_API_LAYER }}
+      APP_VERSION: "v1"
+      API_ID: "${{ needs.pre-deploy-prod-01.outputs.output1 }}"
       CLUSTER_ENABLED_FLAG: "false" #Set to true if needed;
-      #Begin S3 Logging Properties
-      MULE_LOG_S3_FREQUENCY_MIN: "${{ vars.MULE_PROD_LOG_S3_FREQUENCY_MIN }}"
-      MULE_LOG_S3_AWS_REGION: "${{ vars.MULE_LOG_S3_AWS_REGION }}"
-      MULE_LOG_S3_AWS_BUCKET: "${{ vars.MULE_PROD_LOG_S3_AWS_BUCKET }}"
-      MULE_LOG_S3_COMPRESS_FLAG: "${{ vars.MULE_LOG_S3_COMPRESS_FLAG }}"
-      MULE_LOG_S3_STORAGE_CLASS: "${{ vars.MULE_LOG_S3_STORAGE_CLASS }}"
-      #End S3 Logging Properties
     secrets:
       EX_CONNECTED_APP_ID: "${{ secrets.MULE_EX_CONNECTED_APP_ID }}"
       EX_CONNECTED_APP_SECRET: "${{ secrets.MULE_EX_CONNECTED_APP_SECRET }}"
@@ -120,9 +233,39 @@ jobs:
       CH_CONNECTED_APP_SECRET: "${{ secrets.MULE_PROD_CH_CONNECTED_APP_SECRET }}"
       MULE_AP_CLIENT_ID: "${{ secrets.MULE_AP_CLIENT_ID }}"
       MULE_AP_CLIENT_SECRET: "${{ secrets.MULE_AP_CLIENT_SECRET }}"
-      TITAN_BIZ_GROUP: "${{ secrets.MULE_TITAN_BIZ_GROUP }}"
+      BIZ_GROUP: "${{ secrets.MULE_PARENT_BIZ_GROUP }}"
       SECURE_ENCRYPT_KEY: "${{ secrets.MULE_PROD_SECURE_ENCRYPT_KEY }}"
-      #Begin S3 Logging Properties
-      MULE_AWS_S3_ACCESS_KEY: "${{ secrets.MULE_PROD_AWS_S3_ACCESS_KEY }}"
-      MULE_AWS_S3_SECRET_KEY: "${{ secrets.MULE_PROD_AWS_S3_SECRET_KEY }}"
-      #End S3 Logging Properties
+
+  #Post Deployment Job
+  post-deploy-prod-01:
+    if: ${{ github.event.inputs.isPolicyNeeded == '' || github.event.inputs.isPolicyNeeded == 'true' }}
+    runs-on: ubuntu-20.04
+    needs: deploy-prod-01
+    environment:
+      name: "PROD"
+    env:
+      policyFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/policies.yaml"
+      postmanCollectionFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/collection/Email-Sapi.postman_collection.json"
+      postmanEnvFile: "src/main/resources/config/${{ vars.APPLICATION_ENV }}/collection/PROD.postman_environment.json"
+    steps:
+    - uses: actions/checkout@v2
+    - id: RunPostDeploymentScriptFile
+      run: |
+         npm install -g anypoint-cli-v4
+         sudo apt-get update && sudo apt-get -qq -y install jq  
+         sudo apt install libxml2-utils
+         sudo snap install yq
+         chmod +x scripts/deploymentAutomationScript.sh
+         ./scripts/deploymentAutomationScript.sh "PROD" ${{ secrets.MULE_HG_CLI_CLIENT_ID }} ${{ secrets.MULE_HG_CLI_CLIENT_SECRET }} ${{ secrets.MULE_PARENT_BIZ_GROUP }} pom.xml ${{ vars.DEPLOYMENT_TYPE }} ${{ vars.POST_DEPLOYMENT_ACTION }} $policyFile
+    - name: Run postman scripts
+      run: |
+         npm install -g newman
+         npm install -g newman-reporter-htmlextra
+         sleep 60
+         newman run $postmanCollectionFile -e $postmanEnvFile
+          if [ $? -eq 0 ]; then
+            echo "All tests passed successfully."
+          else
+            echo "There were test failures."
+          fi
+      shell: bash
